name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease
      
    # - name: Upload a Build Artifact
    #   uses: actions/upload-artifact@v4.3.3
    #   with:
    #       name: ljjy-apk
    #       path: |
    #         ${{github.workspace}}/app/build/outputs/apk/tencent/release/*.apk
    #         ${{github.workspace}}/app/build/outputs/apk/xiaomi/release/*.apk

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./${{ secrets.ReleaseZipName }}.apk
        asset_name: ${{ secrets.ReleaseZipName }}.apk
        asset_content_type: application/apk
          
