name: Android Package
 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
 
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
 
    - name: Set up Android SDK
      uses: android-actions/sdk-manager@v1
      with:
        permissions: write
 
    - name: Set up Gradle
      uses: gradle/wrapper-action@v1
 
    - name: Build with Gradle
      run: ./gradlew assembleRelease
 
    - name: Upload APK to GitHub Release
      uses: actions/upload-artifact@v1
      if: success()
      with:
        name: apk
        path: app/build/outputs/apk/release/app-release.apk
